[profile.default]
src = "contracts/src"
test = "contracts/test"
script = "contracts/script"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 1
via_ir = true
fuzz = { runs = 512 }
invariant = { runs = 256, depth = 64, fail_on_revert = false }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
quote_style = "double"

[rpc_endpoints]
arc_testnet = "${ARC_TESTNET_RPC_URL}"
