packages:
  - "apps/*"
  - "packages/*"
onlyBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - '@next/env@16.2.11'
  - '@next/eslint-plugin-next@16.2.11'
  - '@next/swc-darwin-arm64@16.2.11'
  - '@next/swc-darwin-x64@16.2.11'
  - '@next/swc-linux-arm64-gnu@16.2.11'
  - '@next/swc-linux-arm64-musl@16.2.11'
  - '@next/swc-linux-x64-gnu@16.2.11'
  - '@next/swc-linux-x64-musl@16.2.11'
  - '@next/swc-win32-arm64-msvc@16.2.11'
  - '@next/swc-win32-x64-msvc@16.2.11'
  - '@tanstack/query-core@5.101.4'
  - '@tanstack/react-query@5.101.4'
  - bullmq@5.80.10
  - eslint-config-next@16.2.11
  - next@16.2.11
  - react-dom@19.2.8
  - react@19.2.8
  - viem@2.55.5
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
  unrs-resolver: true
